[project]
name = "repl-nix-telegramvoiceflowconnector"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "python-telegram-bot==13.7",
    "requests>=2.32.3",
    "telegram",
]
